image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2369.70957,    0.     ,  736.51017,
            0.     , 2364.06471,  567.76429,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.082007, 0.360906, 0.000340, -0.002085, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2358.4729 ,    0.     ,  734.38944,    0.     ,
            0.     , 2355.02783,  567.36665,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
